Repository ithacaxyz/relay, pull requests merged in 2025-09, with the labels that each got.

#1360 fix(metrics): do not checksum address label value for balance metrics
  src/metrics/periodic/types/balance.rs
  tests/e2e/cases/metrics.rs
Labels: bug, observability

#1364 fix: arbitrum gas estimation
  src/provider.rs
  src/rpc/extra_fee.rs
  src/rpc/relay.rs
Labels: bug

#1361 feat: store precalls
  .sqlx/query-349050d675179f714ad8cf61ad13a457aab1a08ffd7d73b63944aeba2fc6a36a.json
  .sqlx/query-7150f186ceabdaa8f4a1245a8986db4d2feed0d9b0a5b689105acc35a764451e.json
  .sqlx/query-a430d775b648600b9648e00c315b75da85e010aa060a31ff44588d4735e23783.json
  migrations/0024_precalls.sql
  src/error/keys.rs
  src/rpc/relay.rs
  src/storage/api.rs
  src/storage/memory.rs
  src/storage/mod.rs
  src/storage/pg.rs
  src/types/account.rs
  src/types/intent/enum.rs
  src/types/intent/mod.rs
  src/types/intent/v04.rs
  src/types/intent/v05.rs
  src/types/rpc/calls.rs
  src/types/storage.rs
  tests/e2e/cases/delegation.rs
  tests/e2e/cases/simple.rs
  tests/e2e/mod.rs
  tests/e2e/types.rs
Labels: enhancement

#1397 feat: return quote signer address in `relay_health`
  src/rpc/relay.rs
  src/types/mod.rs
  tests/e2e/cases/rpc_snap.rs
  tests/e2e/cases/snapshots/tests__e2e__cases__rpc_snap__health.snap
Labels: enhancement
